---
- hosts: all
  become: yes
  gather_facts: no
# публичный ключ репозитория
  tasks:
    - name: "Add apy key for elastic"
      ansible.builtin.apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
#установка пакета apt-transport
    - name: "Install apt source"
      apt:
        name: apt-transport-https
        state: present
#добавление Elastik в систему
    - name: "Add ELK repository"
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        state: present
#установка Elastik
    - name: "Install elastic"
      apt:
        mame: elasticsearch
        state: present
#установка Kibana
    - name: "Install Kibana"
      apt:
        mame: kibana
        state: present

    - name: "Install Logstash"
      apt:
        mame: logstash
        state: present

    - name: "elastic systemd"
      systemd:
        mame: elasticsearch
        state: started
        enabled: yes

    - name: "Kibana systemd"
      systemd:
        mame: Kibana
        state: started
        enabled: yes

  #  - name: "Logstash systemd"
   #   systemd:
    #     mame: logstash
     #    state: started
      #   enabled: yes

    - name: "Prepare configs for logstash"
      copy:
        src: configs/logstash/input.conf
        dest: /etc/logstash/conf.d
        owner: root
        group: root
        mode: 0644
    - name: "..output.conf"
      copy:
        src: configs/logstash/output.conf
        dest: /etc/logstash/conf.d
        owner: root
        group: root
        mode: 0644
    - name: "..filter.conf"
      copy:
        src: configs/logstash/filter.conf
        dest: /etc/logstash/conf.d
        owner: root
        group: root
        mode: 0644

    - name: "Logstash systemd"
      systemd:
        mame: logstash
        state: started
        enabled: yes

